version: '2.2'
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.3
    container_name: kibana
    environment:
      SERVER_NAME: elasticsearch
    ports:
      - 15601:5601
    depends_on:
      - elasticsearch
  
  filebeat:
    build: ./filebeat/
    container_name: filebeat
    depends_on:
      - kibana
      - elasticsearch
    volumes:
      - ./data/filebeat/:/usr/share/filebeat/data/
      - ./logs/:/usr/share/filebeat/logs/
      - "/var/run/docker.sock:/var/run/docker.sock"